import type { EvaluationResponse, VerdictStatus } from '../types';

// Pre-computed verdicts for the five bundled sample bidders against the
// CRPF mock tender. Keyed by a normalised form of the bidder name; matched
// to incoming criteria by ordinal position.
//
// The numbers and dates here line up with the realistic PDFs in
// sample-data/, so the demo always produces:
//   bidder-01 -> eligible
//   bidder-02 -> not_eligible (turnover and solvency below thresholds)
//   bidder-03 -> needs_review (ISO 9001 expires on bid date)
//   bidder-04 -> eligible
//   bidder-05 -> not_eligible (ISO 9001 expired before bid date)

type CachedEvaluation = EvaluationResponse;

interface CachedBidder {
  // Used for fuzzy name match against whatever the user typed when adding the bidder.
  matchKeys: string[];
  evaluations: CachedEvaluation[];
}

const e = (
  status: VerdictStatus,
  confidence: number,
  found_value: string,
  found_unit: string,
  evidence_text: string,
  evidence_doc: string,
  evidence_page: number,
  reasoning: string,
): CachedEvaluation => ({
  status,
  found_value,
  found_unit,
  confidence,
  evidence_text,
  evidence_doc,
  evidence_page,
  reasoning,
});

// Each bidder has 10 entries matching the 10 criteria the tender produces
// (C-1 through C-10 in order). If the user's tender extracts more or fewer
// criteria, the loader falls back to a generic needs_review for the extras.

export const DEMO_BIDDERS: CachedBidder[] = [
  // ---- Sharma Construction (eligible) ----
  {
    matchKeys: ['sharma'],
    evaluations: [
      e('eligible', 0.97, '152000000', 'INR',
        'FY 2024-25: Rs. 15,20,00,000 (Rupees Fifteen Crore Twenty Lakh Only)',
        '02-ca-turnover-certificate.pdf', 1,
        'CA-certified turnover for FY 2024-25 is Rs. 15.2 Cr, well above the Rs. 5 Cr threshold (3.04x).'),
      e('eligible', 0.95, '30000000', 'INR',
        'is solvent to the extent of Rs. 3,00,00,000 (Rupees Three Crore Only)',
        '03-solvency-certificate.pdf', 1,
        'SBI Connaught Place certified solvency of Rs. 3 Cr exceeds the Rs. 2 Cr requirement.'),
      e('eligible', 0.96, '1600000', 'INR',
        'EMD ... Rs. 16,00,000 (Rupees Sixteen Lakh Only) ... HDFC Bank Guarantee BG/2026/04/0119',
        '08-emd-bank-guarantee.pdf', 1,
        'HDFC Bank Guarantee BG/2026/04/0119 dated 05-04-2026 for Rs. 16 Lakh matches the EMD requirement exactly.'),
      e('eligible', 0.93, '5 projects, all > Rs. 2 Cr in 7 yrs', 'count',
        '5 similar institutional projects: ITBP Barrack Leh (Rs. 4.8 Cr, 2024), CISF Office Jaipur (Rs. 6.2 Cr, 2023), BSF Jaisalmer (Rs. 3.9 Cr, 2022)...',
        '07-projects-list.pdf', 1,
        'Five completed institutional projects in the last 7 years, each above Rs. 2 Cr — exceeds the minimum of three.'),
      e('eligible', 0.95, '15 years', 'years',
        'Date of Incorporation: 15-03-2010 (16 years in operation)',
        '06-pan-card.pdf', 1,
        'Incorporated 15-03-2010, giving over 15 years of construction experience as on bid date — well above 5-year minimum.'),
      e('eligible', 0.96, 'GSTIN 07AABCS1234A1Z5 ACTIVE', 'boolean',
        'GSTIN: 07AABCS1234A1Z5 ... Status: ACTIVE — verified on 10-04-2026',
        '04-gst-registration-certificate.pdf', 1,
        'Active GST registration verified within 5 days of bid submission date.'),
      e('eligible', 0.94, 'ISO 9001:2015 valid till 11-08-2028', 'date',
        'Bureau Veritas BV-IN-2023-9001-77821 ... Date of Expiry: 11-08-2028',
        '05-iso-9001-certificate.pdf', 1,
        'ISO 9001:2015 certificate from Bureau Veritas valid until Aug 2028, well past the bid date.'),
      e('eligible', 0.98, 'AABCS1234A', 'text',
        'Permanent Account Number: AABCS1234A',
        '06-pan-card.pdf', 1,
        'PAN card of the firm submitted; format and check digits valid.'),
      e('eligible', 0.92, 'ISO 14001:2015 valid till 30-04-2027', 'date',
        'BV-IN-2024-14001-44120 ... ISO 14001:2015 ... Date of Expiry: 30-04-2027',
        '05b-iso-14001-certificate.pdf', 1,
        'Bidder holds the optional ISO 14001:2015 environmental management certification — bonus weightage applies.'),
      e('eligible', 0.93, '5 paramilitary projects', 'count',
        'CISF Office Complex Jaipur, BSF Family Quarters Jaisalmer, CRPF Mess Hall Hazaribagh, ITBP Barrack Leh',
        '07-projects-list.pdf', 1,
        'Strong track record of CRPF/CISF/BSF/ITBP construction projects — bidder qualifies for the optional paramilitary preference.'),
    ],
  },

  // ---- Gupta Builders (not_eligible — financials below) ----
  {
    matchKeys: ['gupta'],
    evaluations: [
      e('not_eligible', 0.93, '34000000', 'INR',
        'FY 2024-25: Rs. 3,40,00,000 ... FY 2023-24: Rs. 3,10,00,000 ... FY 2022-23: Rs. 2,80,00,000',
        '02-ca-turnover-certificate.pdf', 1,
        'Highest annual turnover (Rs. 3.4 Cr in FY 2024-25) is below the Rs. 5 Cr mandatory threshold. Fails C-1.'),
      e('not_eligible', 0.91, '15000000', 'INR',
        'is solvent to the extent of Rs. 1,50,00,000 (Rupees One Crore Fifty Lakh Only)',
        '03-solvency-certificate.pdf', 1,
        'PNB-certified solvency of Rs. 1.5 Cr is below the Rs. 2 Cr minimum. Fails C-2.'),
      e('eligible', 0.95, '1600000', 'INR',
        'PNB Bank Guarantee BG No. PNB/BG/2026/0455 dated 08-04-2026 for Rs. 16,00,000',
        '08-emd-bank-guarantee.pdf', 1,
        'EMD of Rs. 16 Lakh submitted via PNB Bank Guarantee — meets requirement.'),
      e('eligible', 0.86, '4 projects, all > Rs. 2 Cr in 7 yrs', 'count',
        'Apartment Block Faridabad Rs. 2.4 Cr (2023); PHC Rohtak Rs. 2.1 Cr (2022); School Karnal Rs. 2.6 Cr (2021); Community Hall Sonipat Rs. 2.15 Cr (2020)',
        '07-projects-list.pdf', 1,
        'Four similar projects within last 7 years, all above Rs. 2 Cr.'),
      e('eligible', 0.94, '8 years', 'years',
        'Date of Establishment: 01-08-2017',
        '06-pan-card.pdf', 1,
        'Established 2017, ~8 years of construction experience — exceeds 5-year minimum.'),
      e('eligible', 0.95, 'GSTIN 07AAFFG7654B1ZK ACTIVE', 'boolean',
        'GSTIN: 07AAFFG7654B1ZK ... Status: ACTIVE',
        '04-gst-registration-certificate.pdf', 1,
        'GST registration is active.'),
      e('eligible', 0.92, 'ISO 9001:2015 valid till 30-04-2027', 'date',
        'TUV-IN-2024-90001-66312 ... Date of Expiry: 30-04-2027',
        '05-iso-9001-certificate.pdf', 1,
        'TUV India ISO 9001:2015 certificate valid till April 2027.'),
      e('eligible', 0.97, 'AAFFG7654B', 'text',
        'PAN: AAFFG7654B',
        '06-pan-card.pdf', 1,
        'PAN card of the firm submitted; valid format.'),
      e('not_eligible', 0.7, 'Not provided', 'boolean',
        '',
        '', 0,
        'No ISO 14001 certificate found in submitted documents.'),
      e('not_eligible', 0.8, 'No paramilitary projects in list', 'count',
        'Apartment, PHC, School, Community Hall — all civilian local-government projects',
        '07-projects-list.pdf', 1,
        'No CRPF / BSF / ITBP / SSB / CISF or armed-forces project history in the submitted projects list.'),
    ],
  },

  // ---- National Infrastructure Corp (needs_review) ----
  {
    matchKeys: ['national', 'infrastructure'],
    evaluations: [
      e('needs_review', 0.62, '72000000 (provisional)', 'INR',
        'FY 2024-25: Rs. 7,20,00,000 — Note: figures provisional, audit in progress',
        '02-ca-turnover-certificate.pdf', 1,
        'FY 2024-25 turnover of Rs. 7.2 Cr would meet the Rs. 5 Cr threshold but the CA flags the figure as provisional pending audit. Needs verification.'),
      e('eligible', 0.84, '25000000', 'INR',
        'M/s National Infrastructure Corp is solvent to the extent of Rs. 2,50,00,000',
        '03-solvency-certificate.pdf', 1,
        'BoB Sector-18 Noida certified solvency of Rs. 2.5 Cr meets the Rs. 2 Cr requirement; certificate is within 6-month validity window.'),
      e('eligible', 0.91, '1600000', 'INR',
        'Demand Draft No. BOB/DD/2026/04/0231 ... Rs. 16,00,000',
        '08-emd-bank-guarantee.pdf', 1,
        'EMD of Rs. 16 Lakh submitted via Bank of Baroda Demand Draft.'),
      e('needs_review', 0.55, '3 projects with one borderline',
        'count',
        'PWD Rest House Allahabad — Completed 30-09-2018 (note: just outside the 7-year window relative to bid date 15-04-2026)',
        '07-projects-list.pdf', 1,
        'Three similar projects listed but the 2018 PWD project is borderline outside the 7-year window. Needs human review of date interpretation.'),
      e('needs_review', 0.65, '6 years 5 months', 'years',
        'Date of Incorporation: 20-11-2019 (about 6 years 5 months as on bid date)',
        '06-pan-card.pdf', 1,
        'Experience of ~6.5 years exceeds the 5-year minimum — eligible on numbers, but cover letter notes audit pending; flagging for due diligence.'),
      e('needs_review', 0.6, 'GSTIN 09AAACN9876C1Z2 (verification partial)', 'boolean',
        'GSTIN: 09AAACN9876C1Z2 ... Status: ACTIVE (verification partial — see note)',
        '04-gst-registration-certificate.pdf', 1,
        'GST appears active but the bidder flags partial verification. Needs verification on GSTN portal.'),
      e('needs_review', 0.45, 'ISO 9001:2015 expires on bid date', 'date',
        'Date of Expiry: 15-04-2026 ... NOTE: This certificate expires on the date of bid submission itself.',
        '05-iso-9001-certificate.pdf', 1,
        'ISO 9001:2015 certificate expires on the bid submission date itself — edge case requiring human judgement on whether "valid as on date" includes the expiry date.'),
      e('eligible', 0.95, 'AAACN9876C', 'text',
        'PAN: AAACN9876C',
        '06-pan-card.pdf', 1,
        'PAN card of the firm submitted; valid format.'),
      e('not_eligible', 0.7, 'Not provided', 'boolean',
        '',
        '', 0,
        'No ISO 14001 certificate found in submitted documents.'),
      e('not_eligible', 0.7, 'No paramilitary projects in list', 'count',
        'UP Govt Office, Boys Hostel BHU, PWD Rest House — civilian projects',
        '07-projects-list.pdf', 1,
        'No paramilitary or armed-forces construction history in the submitted list.'),
    ],
  },

  // ---- Apex Constructions (eligible) ----
  {
    matchKeys: ['apex'],
    evaluations: [
      e('eligible', 0.98, '180000000', 'INR',
        'FY 2024-25: Rs. 18,00,00,000 (Rupees Eighteen Crore Only)',
        '02-ca-turnover-certificate.pdf', 1,
        'CA-certified FY 2024-25 turnover of Rs. 18 Cr is 3.6x the Rs. 5 Cr threshold.'),
      e('eligible', 0.97, '40000000', 'INR',
        'is solvent to the extent of Rs. 4,00,00,000 (Rupees Four Crore Only)',
        '03-solvency-certificate.pdf', 1,
        'ICICI Mumbai Main certified solvency of Rs. 4 Cr is 2x the Rs. 2 Cr requirement.'),
      e('eligible', 0.96, '1600000', 'INR',
        'ICICI Bank Guarantee BG/2026/04/0341 dated 04-04-2026 for Rs. 16,00,000',
        '08-emd-bank-guarantee.pdf', 1,
        'EMD of Rs. 16 Lakh via ICICI Bank Guarantee — matches requirement.'),
      e('eligible', 0.96, '7 paramilitary/defence projects in 7 yrs, all > Rs. 2 Cr', 'count',
        'IAF HQ Pune Rs. 8.9 Cr (2024); Naval Mess Vizag Rs. 6.4 Cr (2023); CRPF Group Centre Avadi Rs. 9.2 Cr (2022); CISF HQ Annexe Gurugram Rs. 5.8 Cr (2021)...',
        '07-projects-list.pdf', 1,
        'Seven completed paramilitary / defence projects, all above Rs. 2 Cr — strongly exceeds three-project minimum.'),
      e('eligible', 0.96, '15 years', 'years',
        'Date of Incorporation: 25-08-2010',
        '06-pan-card.pdf', 1,
        'Incorporated August 2010, ~15 years construction experience — well above 5-year minimum.'),
      e('eligible', 0.97, 'GSTIN 27AAACA5566D1Z9 ACTIVE', 'boolean',
        'GSTIN: 27AAACA5566D1Z9 ... Status: ACTIVE',
        '04-gst-registration-certificate.pdf', 1,
        'Active GST registration on Maharashtra state code.'),
      e('eligible', 0.95, 'ISO 9001:2015 valid till 31-05-2027', 'date',
        'DNV-9001-2024-02112 ... Date of Expiry: 31-05-2027',
        '05-iso-9001-certificate.pdf', 1,
        'DNV-GL India ISO 9001:2015 certificate valid until May 2027.'),
      e('eligible', 0.98, 'AAACA5566D', 'text',
        'PAN: AAACA5566D',
        '06-pan-card.pdf', 1,
        'PAN card of the firm submitted; valid format.'),
      e('not_eligible', 0.6, 'Not provided', 'boolean',
        '',
        '', 0,
        'No ISO 14001 certificate found in submitted documents (preferred criterion).'),
      e('eligible', 0.97, '7 paramilitary/defence projects', 'count',
        'IAF Station HQ Pune; Naval Officers Mess Visakhapatnam; CRPF Group Centre Avadi; CISF HQ Annexe; BSF Hospital; SSB Training Centre; Coast Guard Quarters',
        '07-projects-list.pdf', 1,
        'Extensive paramilitary and armed-forces construction history including direct CRPF work — strong fit for preferred criterion.'),
    ],
  },

  // ---- Metro Build Solutions (not_eligible — ISO expired) ----
  {
    matchKeys: ['metro'],
    evaluations: [
      e('eligible', 0.93, '62000000', 'INR',
        'FY 2024-25: Rs. 6,20,00,000',
        '02-ca-turnover-certificate.pdf', 1,
        'CA-certified FY 2024-25 turnover of Rs. 6.2 Cr exceeds the Rs. 5 Cr threshold.'),
      e('eligible', 0.92, '20000000', 'INR',
        'Solvency: Rs. 2,00,00,000 (Rupees Two Crore Only)',
        '03-solvency-certificate.pdf', 1,
        'Axis Bank Civil Lines certified solvency of Rs. 2 Cr meets the Rs. 2 Cr minimum exactly.'),
      e('eligible', 0.93, '1600000', 'INR',
        'Demand Draft No. AXIS/DD/2026/04/0099 ... Rs. 16,00,000',
        '08-emd-bank-guarantee.pdf', 1,
        'EMD of Rs. 16 Lakh submitted via Axis Bank Demand Draft.'),
      e('eligible', 0.86, '3 projects > Rs. 2 Cr in 7 yrs', 'count',
        'PWD Office Nagpur Rs. 2.3 Cr (2024); Polytechnic Workshop Nashik Rs. 2.9 Cr (2023); Bus Depot Aurangabad Rs. 2.15 Cr (2022)',
        '07-projects-list.pdf', 1,
        'Three completed institutional projects, all above Rs. 2 Cr — meets minimum of three exactly.'),
      e('eligible', 0.94, '7 years', 'years',
        'Date of Incorporation: 12-04-2018',
        '06-pan-card.pdf', 1,
        'Incorporated April 2018, ~7 years construction experience — exceeds 5-year minimum.'),
      e('eligible', 0.95, 'GSTIN 27AAACM3344E1Z3 ACTIVE', 'boolean',
        'GSTIN: 27AAACM3344E1Z3 ... Status: ACTIVE',
        '04-gst-registration-certificate.pdf', 1,
        'Active GST registration on Maharashtra state code.'),
      e('not_eligible', 0.95, 'ISO 9001:2015 EXPIRED 30-06-2025', 'date',
        'Date of Expiry: 30-06-2025 ... NOTE: This certificate has LAPSED. Renewal application filed but not yet completed.',
        '05-iso-9001-certificate.pdf', 1,
        'ISO 9001:2015 certificate expired on 30-06-2025, ~9 months before bid submission date 15-04-2026. Fails C-7 (must be valid as on date of bid submission).'),
      e('eligible', 0.97, 'AAACM3344E', 'text',
        'PAN: AAACM3344E',
        '06-pan-card.pdf', 1,
        'PAN card of the firm submitted; valid format.'),
      e('not_eligible', 0.6, 'Not provided', 'boolean',
        '',
        '', 0,
        'No ISO 14001 certificate found in submitted documents.'),
      e('not_eligible', 0.7, 'No paramilitary projects in list', 'count',
        'PWD Office, Polytechnic, Bus Depot — state-government civil projects',
        '07-projects-list.pdf', 1,
        'No CRPF / BSF / ITBP / armed-forces construction history in submitted list.'),
    ],
  },
];

// Healthcare tender bidders (AIIMS ventilator procurement, 11 criteria).
// Order: C-1 CDSCO, C-2 ISO 13485, C-3 IEC 60601, C-4 5+ years experience,
//        C-5 3+ similar supplies > 50L, C-6 turnover >= 10 Cr, C-7 net worth >= 5 Cr,
//        C-8 GST active, C-9 service network 10+ cities, C-10 ISO 9001 (preferred),
//        C-11 Make in India / DPIIT (preferred).
export const HEALTHCARE_DEMO_BIDDERS: CachedBidder[] = [
  {
    matchKeys: ['meditech'],
    evaluations: [
      e('eligible', 0.96, 'CDSCO MFG/MD/2024/0091 valid till 14-06-2029', 'date',
        'License Number: MFG/MD/2024/0091 ... Date of Expiry: 14-06-2029',
        '03-cdsco-manufacturing-license.pdf', 1,
        'Valid CDSCO Form MD-9 manufacturing licence covering "Adult Mechanical Ventilator (Class C)" till June 2029.'),
      e('eligible', 0.95, 'ISO 13485:2016 valid till 30-06-2027', 'date',
        'TUV-IN-2024-13485-22311 ... Date of Expiry: 30-06-2027',
        '04-iso-13485-certificate.pdf', 1,
        'ISO 13485:2016 from TUV India valid till June 2027, scope explicitly covers mechanical ventilators.'),
      e('eligible', 0.94, 'IEC 60601-1 / 60601-2-12 valid till 11-09-2027', 'date',
        'ETDC-IEC-60601-2024-1188 ... Date of Expiry: 11-09-2027',
        '05-iec-60601-compliance.pdf', 1,
        'NABL-accredited ETDC test report for IEC 60601-1 and 60601-2-12 valid till Sep 2027.'),
      e('eligible', 0.93, '12 years', 'years',
        'Date of Incorporation: 15-04-2014 (12 years in operation)',
        '07-pan-card.pdf', 1,
        '12 years in medical device supply, well above the 5-year minimum.'),
      e('eligible', 0.95, '5 ventilator orders > Rs. 50 lakh in last 5 yrs', 'count',
        'AIIMS Bhubaneswar Rs. 65 Lakh (2024); PGIMER Chandigarh Rs. 54 Lakh (2024); JIPMER Rs. 78 Lakh (2023)...',
        '09-similar-supply-list.pdf', 1,
        'Five completed ventilator supplies above the Rs. 50 lakh threshold within the 5-year window.'),
      e('eligible', 0.97, '152000000', 'INR',
        'FY 2024-25: Rs. 15,20,00,000',
        '02-ca-turnover-certificate.pdf', 1,
        'CA-certified FY 2024-25 turnover of Rs. 15.2 Cr exceeds the Rs. 10 Cr threshold (1.5x).'),
      e('eligible', 0.85, 'Net worth derivable from CA cert, ~Rs. 6+ Cr', 'INR',
        'CA certificate signed by Krishnan Iyer & Co., FRN 023411S',
        '02-ca-turnover-certificate.pdf', 1,
        'CA-certified turnover position implies net worth above the Rs. 5 Cr requirement; full net-worth cert can be requested at LoA stage.'),
      e('eligible', 0.96, 'GSTIN 06AAACM4421T1Z9 ACTIVE', 'boolean',
        'GSTIN: 06AAACM4421T1Z9 ... Status: ACTIVE',
        '06-gst-registration-certificate.pdf', 1,
        'Active GST registration on Haryana state code.'),
      e('eligible', 0.95, '22 cities, 84 biomed engineers', 'count',
        'Total cities covered: 22 ... Total biomedical engineers on payroll: 84',
        '08-service-network-statement.pdf', 1,
        '22-city service network covers all five tier-1 cities and all four metros — comfortably exceeds 10-city minimum.'),
      e('eligible', 0.93, 'ISO 9001:2015 valid till 30-06-2027', 'date',
        'TUV-IN-2024-90001-44199 ... Date of Expiry: 30-06-2027',
        '11-iso-9001-certificate.pdf', 1,
        'Bidder also holds the optional ISO 9001:2015 in addition to ISO 13485 — preferred criterion satisfied.'),
      e('not_eligible', 0.5, 'Not declared', 'boolean',
        '',
        '', 0,
        'Make in India / DPIIT local-content declaration not found among submitted documents.'),
    ],
  },

  {
    matchKeys: ['lifeline'],
    evaluations: [
      e('not_eligible', 0.94, 'No CDSCO Form MD-9 / MD-5; only MD-15 importer registration', 'boolean',
        '"We are NOT a manufacturer; we operate as an authorised distributor. CDSCO Form MD-15 (Importer Registration) is enclosed. OEM authorisation letter is being sought..."',
        '01-cover-letter.pdf', 1,
        'Bidder is an importer, not an OEM manufacturer. Only CDSCO Form MD-15 is held; the tender requires Form MD-9/MD-5 OR a valid OEM authorisation, neither of which is currently submitted. Fails C-1.'),
      e('eligible', 0.92, 'ISO 13485:2016 valid till 31-07-2027', 'date',
        'INT-13485-2024-09127 ... Date of Expiry: 31-07-2027',
        '04-iso-13485-certificate.pdf', 1,
        'Intertek-issued ISO 13485:2016 covers distribution and after-sales service of medical devices.'),
      e('not_eligible', 0.7, 'No IEC 60601 test report submitted', 'boolean',
        'No IEC 60601 compliance test report enclosed in the submission set',
        '', 0,
        'Bidder relies on imported OEM compliance but did not enclose any IEC 60601-1 / 60601-2-12 test report. Fails C-3.'),
      e('eligible', 0.88, '~7 years', 'years',
        'Date of Incorporation: 20-06-2019 (~7 years)',
        '07-pan-card.pdf', 1,
        'Operational since 2019 — ~7 years experience meets the 5-year minimum.'),
      e('not_eligible', 0.85, '0 ventilator supplies > Rs. 50 lakh', 'count',
        'GMC Indore — 8 ventilators (imported) — Rs. 32 lakh (2024); other supplies are monitors / pumps below threshold',
        '09-similar-supply-list.pdf', 1,
        'No ventilator supply order at or above Rs. 50 lakh in the last 5 years (largest is Rs. 32 lakh). Fails C-5.'),
      e('not_eligible', 0.93, '72000000', 'INR',
        'FY 2024-25: Rs. 7,20,00,000',
        '02-ca-turnover-certificate.pdf', 1,
        'Highest annual turnover (Rs. 7.2 Cr) is below the Rs. 10 Cr mandatory threshold. Fails C-6.'),
      e('not_eligible', 0.7, 'Net worth not certified, derived <Rs. 5 Cr', 'INR',
        '',
        '', 0,
        'No standalone net-worth certificate; derivable estimate from CA cert is below Rs. 5 Cr.'),
      e('eligible', 0.95, 'GSTIN 07AAFFL5511P1ZN ACTIVE', 'boolean',
        'GSTIN: 07AAFFL5511P1ZN ... Status: ACTIVE',
        '06-gst-registration-certificate.pdf', 1,
        'GST registration is active on Delhi state code.'),
      e('not_eligible', 0.92, '7 cities only', 'count',
        'Total cities covered: 7',
        '08-service-network-statement.pdf', 1,
        'Service network covers only 7 cities — below the 10-city minimum. Fails C-9.'),
      e('not_eligible', 0.6, 'ISO 9001 not enclosed', 'boolean',
        '',
        '', 0,
        'No ISO 9001:2015 certificate found among submitted documents (preferred criterion).'),
      e('not_eligible', 0.5, 'Not declared', 'boolean',
        '',
        '', 0,
        'Make in India / DPIIT local-content declaration not found.'),
    ],
  },

  {
    matchKeys: ['pinnacle'],
    evaluations: [
      e('needs_review', 0.4,
        'CDSCO MFG/MD/2021/0334 expired 11-04-2026 (4 days before bid date)',
        'date',
        'Date of Expiry: 11-04-2026 ... NOTE: This license expired four days before the bid submission. Renewal application is in process.',
        '03-cdsco-manufacturing-license.pdf', 1,
        'CDSCO manufacturing licence expired four days before bid submission. Renewal pending — edge case requiring officer judgement on whether substantive compliance is acceptable. Fails strict reading; needs review.'),
      e('eligible', 0.92, 'ISO 13485:2016 valid till 19-08-2026', 'date',
        'DNV-13485-2023-09812 ... Date of Expiry: 19-08-2026',
        '04-iso-13485-certificate.pdf', 1,
        'DNV-GL ISO 13485:2016 valid as on bid date.'),
      e('needs_review', 0.45,
        'IEC 60601 compliance expired 03-04-2026 (12 days before bid date)',
        'date',
        'Date of Expiry: 03-04-2026 ... NOTE: This compliance test report expired 12 days prior to bid submission.',
        '05-iec-60601-compliance.pdf', 1,
        'IEC 60601 test report expired 12 days before bid date. Re-testing booked but not concluded. Officer must decide whether re-testing in progress is acceptable.'),
      e('eligible', 0.91, '~7 years 8 months', 'years',
        'Date of Incorporation: 12-08-2018',
        '07-pan-card.pdf', 1,
        'Operational since Aug 2018, ~7.7 years experience exceeds the 5-year minimum.'),
      e('eligible', 0.85, '3 ventilator supplies > Rs. 50 lakh', 'count',
        'AIIMS Bhopal Rs. 58 Lakh (2024); NIMHANS Rs. 34 Lakh (2023); KMC Manipal Rs. 28 Lakh (2021)',
        '09-similar-supply-list.pdf', 1,
        'Three similar supplies listed but only AIIMS Bhopal (Rs. 58 lakh) clearly meets the Rs. 50 lakh threshold; the others fall short.'),
      e('needs_review', 0.6, '112000000 (provisional)', 'INR',
        'FY 2024-25 (Provisional): Rs. 11,20,00,000 — Note: figures provisional, audit in progress',
        '02-ca-turnover-certificate.pdf', 1,
        'FY 2024-25 turnover of Rs. 11.2 Cr would meet Rs. 10 Cr threshold but the CA flags figure as provisional pending audit. Needs verification on audited financials.'),
      e('needs_review', 0.55, 'Net worth not separately certified', 'INR',
        '',
        '', 0,
        'Net-worth certificate as on 31-03-2025 not enclosed; needs to be requested before award.'),
      e('eligible', 0.95, 'GSTIN 29AAACP9982R1ZQ ACTIVE', 'boolean',
        'GSTIN: 29AAACP9982R1ZQ ... Status: ACTIVE',
        '06-gst-registration-certificate.pdf', 1,
        'Active GST registration on Karnataka state code.'),
      e('eligible', 0.86, '11 cities', 'count',
        'Total cities covered: 11',
        '08-service-network-statement.pdf', 1,
        '11-city service network meets the 10-city minimum, though tier-1 city coverage outside Bengaluru / Mumbai is thin.'),
      e('not_eligible', 0.6, 'ISO 9001 not enclosed', 'boolean',
        '',
        '', 0,
        'No ISO 9001:2015 certificate found (preferred criterion).'),
      e('not_eligible', 0.5, 'Not declared', 'boolean',
        '',
        '', 0,
        'Make in India / DPIIT local-content declaration not found.'),
    ],
  },

  {
    matchKeys: ['jeevan'],
    evaluations: [
      e('eligible', 0.97, 'CDSCO MFG/MD/2023/0188 valid till 19-03-2028', 'date',
        'License Number: MFG/MD/2023/0188 ... Date of Expiry: 19-03-2028',
        '03-cdsco-manufacturing-license.pdf', 1,
        'Valid CDSCO Form MD-9 covering Adult Mechanical Ventilator (Class C) till March 2028; covers 5 device categories.'),
      e('eligible', 0.96, 'ISO 13485:2016 valid till 14-05-2027', 'date',
        'BV-IN-2024-13485-66102 ... Date of Expiry: 14-05-2027',
        '04-iso-13485-certificate.pdf', 1,
        'Bureau Veritas ISO 13485:2016 valid till May 2027; scope covers mechanical ventilators.'),
      e('eligible', 0.96, 'IEC 60601 / 60601-2-12 valid till 19-08-2027', 'date',
        'STQC-IEC-60601-2024-3322 ... Date of Expiry: 19-08-2027',
        '05-iec-60601-compliance.pdf', 1,
        'STQC (NABL-accredited) test report for IEC 60601-1 and 60601-2-12 valid till Aug 2027.'),
      e('eligible', 0.95, '15 years', 'years',
        'Date of Incorporation: 08-11-2010',
        '07-pan-card.pdf', 1,
        'Established Nov 2010, 15 years experience — well above 5-year minimum.'),
      e('eligible', 0.97, '6 ventilator supplies > Rs. 50 lakh in last 5 yrs', 'count',
        'AIIMS Rishikesh Rs. 78 Lakh (2024); KGMU Rs. 62 Lakh (2024); SGPGI Rs. 56 Lakh (2023); AIIMS Jodhpur Rs. 44 Lakh (2023); JIPMER Rs. 68 Lakh (2022); TMH Rs. 52 Lakh (2021)',
        '09-similar-supply-list.pdf', 1,
        'Six completed ventilator supplies above Rs. 50 lakh in the 5-year window — comfortably exceeds the 3-order minimum.'),
      e('eligible', 0.98, '220000000', 'INR',
        'FY 2024-25: Rs. 22,00,00,000',
        '02-ca-turnover-certificate.pdf', 1,
        'CA-certified FY 2024-25 turnover of Rs. 22 Cr is 2.2x the Rs. 10 Cr threshold.'),
      e('eligible', 0.9, 'Net worth Rs. 8.4 Cr (declared)', 'INR',
        'Net worth as on 31-03-2025 is Rs. 8.4 Crore',
        '01-cover-letter.pdf', 1,
        'Declared net worth of Rs. 8.4 Cr exceeds the Rs. 5 Cr requirement; CA-certified balance sheet to be obtained at LoA stage.'),
      e('eligible', 0.97, 'GSTIN 27AAACJ7711K1ZP ACTIVE', 'boolean',
        'GSTIN: 27AAACJ7711K1ZP ... Status: ACTIVE',
        '06-gst-registration-certificate.pdf', 1,
        'Active GST registration on Maharashtra state code.'),
      e('eligible', 0.97, '28 cities, 110+ biomed engineers', 'count',
        'Total cities covered: 28 ... Total biomedical engineers on payroll: 119',
        '08-service-network-statement.pdf', 1,
        '28-city PAN-India service network with 119 biomedical engineers — strongly exceeds 10-city minimum.'),
      e('eligible', 0.94, 'ISO 9001:2015 valid till 14-05-2027', 'date',
        'BV-IN-2024-90001-66103 ... Date of Expiry: 14-05-2027',
        '11-iso-9001-certificate.pdf', 1,
        'ISO 9001:2015 from Bureau Veritas valid till May 2027 — preferred criterion satisfied.'),
      e('eligible', 0.92, 'DPIIT local supplier, 78% local content', 'boolean',
        'DPIIT-registered Class-I local supplier under Make in India with 78% local content for the JBM-Vent-Pro',
        '01-cover-letter.pdf', 1,
        'DPIIT-registered Class-I local supplier with declared 78% local content — preferred Make-in-India criterion satisfied.'),
    ],
  },

  {
    matchKeys: ['universalhospital', 'universalhe'],
    evaluations: [
      e('eligible', 0.94, 'CDSCO MFG/MD/2022/0411 valid till 14-09-2027', 'date',
        'License Number: MFG/MD/2022/0411 ... Date of Expiry: 14-09-2027',
        '03-cdsco-manufacturing-license.pdf', 1,
        'Valid CDSCO Form MD-9 for Adult Mechanical Ventilator till Sep 2027.'),
      e('eligible', 0.92, 'ISO 13485:2016 valid till 30-11-2026', 'date',
        'UL-IN-2023-13485-22087 ... Date of Expiry: 30-11-2026',
        '04-iso-13485-certificate.pdf', 1,
        'Underwriters Laboratories ISO 13485:2016 valid till Nov 2026.'),
      e('not_eligible', 0.85, 'IEC 60601 expired 19-04-2026 (4 days after bid date)', 'date',
        'Date of Expiry: 19-04-2026',
        '05-iec-60601-compliance.pdf', 1,
        'IEC 60601 compliance test report expires four days AFTER bid submission. The tender requires validity "as on the bid submission date" so this technically passes — however, given the imminent expiry and no renewal evidence, flagging as non-compliant is the safer reading. Will be marked needs-review by some officers.'),
      e('eligible', 0.91, '~8.5 years', 'years',
        'Date of Incorporation: 04-09-2017',
        '07-pan-card.pdf', 1,
        '~8.5 years experience exceeds 5-year minimum.'),
      e('not_eligible', 0.9, '0 ventilator supplies > Rs. 50 lakh', 'count',
        'GMCH Nagpur Rs. 28 Lakh (2024); AIIMS Nagpur Rs. 24 Lakh (2023); GMC Bhopal Rs. 22 Lakh (2022)',
        '09-similar-supply-list.pdf', 1,
        'Largest ventilator supply on record is Rs. 28 Lakh, well below the Rs. 50 lakh threshold. Fails C-5.'),
      e('not_eligible', 0.94, '68000000', 'INR',
        'FY 2024-25: Rs. 6,80,00,000',
        '02-ca-turnover-certificate.pdf', 1,
        'Highest annual turnover (Rs. 6.8 Cr in FY 2024-25) is below the Rs. 10 Cr mandatory threshold. Fails C-6.'),
      e('not_eligible', 0.85, 'Net worth Rs. 4.2 Cr (declared)', 'INR',
        'Net worth as on 31-03-2025 is Rs. 4.2 Crore',
        '01-cover-letter.pdf', 1,
        'Declared net worth of Rs. 4.2 Cr is below the Rs. 5 Cr minimum. Fails C-7.'),
      e('eligible', 0.94, 'GSTIN 27AAFFU3344Q1Z6 ACTIVE', 'boolean',
        'GSTIN: 27AAFFU3344Q1Z6 ... Status: ACTIVE',
        '06-gst-registration-certificate.pdf', 1,
        'Active GST registration on Maharashtra state code.'),
      e('not_eligible', 0.93, '7 cities only', 'count',
        'Total cities covered: 7',
        '08-service-network-statement.pdf', 1,
        'Service network covers only 7 cities (mostly within Maharashtra and central India) — below the 10-city minimum. Fails C-9.'),
      e('not_eligible', 0.6, 'ISO 9001 not enclosed', 'boolean',
        '',
        '', 0,
        'No ISO 9001:2015 certificate found (preferred criterion).'),
      e('not_eligible', 0.5, 'Not declared', 'boolean',
        '',
        '', 0,
        'Make in India / DPIIT local-content declaration not found.'),
    ],
  },
];

// Combined cache that getDemoEvaluationsForBidder() searches.
const ALL_DEMO_BIDDERS: CachedBidder[] = [...DEMO_BIDDERS, ...HEALTHCARE_DEMO_BIDDERS];

function normalize(s: string): string {
  return s.toLowerCase().replace(/[^a-z0-9]/g, '');
}

export function getDemoEvaluationsForBidder(
  bidderName: string,
): CachedEvaluation[] | null {
  const target = normalize(bidderName);
  for (const cached of ALL_DEMO_BIDDERS) {
    for (const k of cached.matchKeys) {
      if (target.includes(normalize(k))) return cached.evaluations;
    }
  }
  return null;
}

export function genericNeedsReview(criterion_code: string): CachedEvaluation {
  return {
    status: 'needs_review',
    found_value: '',
    found_unit: 'text',
    confidence: 0.4,
    evidence_text: '',
    evidence_doc: '',
    evidence_page: 0,
    reasoning: `[demo mode] No cached response available for ${criterion_code}.`,
  };
}
